version: "3.8"
services:
  shiny:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3838"           # host:container
    env_file:
      - stack.env             # provided by Portainer when you "Load variables from .env"
    environment:
      APPLICATION_LOGS_TO_STDOUT: "true"  # see rocker docs